### ISSUE TITLE
MacTex 2015 编译 xelatex main 出错

### ISSUE THREAD

**Issue by mcf171** [xueruini/thuthesis#153] opened 2015-11-12 17:38 UTC
按照 thuthesis.pdf 上首先 latex thuthesis.ins。
然后将生成的文件
thuthesis.cls
thuthesis.cfg
放到/usr/local/texlive/2015/texmf-dist/tex/latex/thuthesis下。
执行xelatex main报错。

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 系 别

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 专 业

Underfull \hbox (badness 10000) detected at line 37
\EU1/FangSong(0)/m/n/16.06 姓 名
[1] [2]

LaTeX Font Warning: Font shape `EU1/TimesNewRoman(0)/m/sc' undefined
(Font)              using `EU1/TimesNewRoman(0)/m/n' instead on input line 37.

[1] [2] (./main.toc) (./data/denotation.tex [3] [4]) [5] (./data/chap01.tex
! Illegal unit of measure (pt inserted).
<to be read again> 
                   \global 
l.7 \chapter{带 English 的标题}

在问题区有看见说用修改后的模板编译正确，不知道是指什么修改。麻烦各位了

https://github.com/xueruini/thuthesis/issues/149

**Comment by xueruini** [comment] 2015-11-13 02:58
> 放到/usr/local/texlive/2015/texmf-dist/tex/latex/thuthesis下。
> 执行xelatex main报错。

在本地就可以了，不必放到系统目录。

> [1] 2 (./data/denotation.tex [3] [4]) [5] (./data/chap01.tex
! Illegal unit of measure (pt inserted).

https://github.com/xueruini/thuthesis/issues/126#issuecomment-111719410

**Comment by alick** [comment] 2015-11-16 04:22
duplicate of #126 , should be fixed in #154

**Closed by alick** 2015-11-16 04:22 UTC
Labels: duplicate
